image: Visual Studio 2019

environment:
  matrix:
    - RUBY_VERSION: "27-x64"

cache:
  - vendor/bundle

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle install

build: off

before_build:
  - ruby -v
  - gem -v
  - bundle -v

build_script:
  - git submodule update --init --recursive
  - bundle exec rake compile -rdevkit

test_script:
  - bundle exec rake test
